#Server port
server:
 port: 8888
 
#spring.profiles.active=local
#Git repo location
spring:
 cloud:
  config:
   server:
    git:
     uri: C:\\Users\\Windows\\Project\\SpringCloudRepo
     cloneOnStart: true

