spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

msg: I am test-refresh Env
