spring:
 config:
  import: optional:configserver:http://localhost:8888
 cloud:
  vault:
   uri: http://localhost:8200
   token: 00000000-0000-0000-0000-000000000000
   generic: 
    enabled: true
    backend: codeusingjava
    default-context: credentials
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
#
#  vault:
#   uri: http://localhost:8200
#   token: 00000000-0000-0000-0000-000000000000
#   generic: 
#    enabled: true
#    backend: codeusingjava
#    default-context: credentials




#    mysql:
#        enabled: true
#        role: readonly
#        backend: mysql
#        username-property: spring.datasource.username
#        password-property: spring.datasource.password