#Server port
server:
 port: 8888
 
#spring.profiles.active=local
#Git repo location
spring:
 cloud:
  config:
   server:
    git:
     uri: C:\\Users\\Windows\\eclipse-workspace\\Git\\SpringCloudRepo
     cloneOnStart: true
    bootstrap: true
  vault:
   uri: http://localhost:8200
   token: 00000000-0000-0000-0000-000000000000
   generic: 
    enabled: true
    backend: codeusingjava
    default-context: credentials
    
management:
 security:
  enabled: false
  
  spring.

spring.cloud.vault.uri=
spring.cloud.vault.token=
spring.cloud.vault.generic.enabled=true
spring.cloud.vault.generic.backend=codeusingjava
spring.cloud.vault.generic.default-context=credentials